export const GET_AUTH_INFO = "GET_AUTH_INFO";
export const GET_USER_PROFILE_COMPLETE = "GET_USER_PROFILE_COMPLETE";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORY_PLAYLISTS = "GET_CATEGORY_PLAYLISTS";